version: '3.8'

services:
  app:
    build:
      context: whatxd/front:latest
    networks:
      - app-network
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    
  app:
    build:
      context: whatxd/back:latest
    networks:
      - app-network
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
      - media_volume:/media
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge
