version: '3.8'

services:
  front:
    build:
      context: whatxd/front:latest
    networks:
      - app-network
    
  back:
    build:
      context: whatxd/back:latest
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - back
      - front

networks:
  app-network:
    driver: bridge
